-- can shoot a ship after it is dead
-- turret disappears sometimes
-- ghost should have some visual appearance
-- remove clouds from planet?
-- planet should be collideable
-- use physics for collisions